<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Spatula Light MVC</title>
<?php echo $this->renderElements('link') ?>
<script type="text/javascript">
SKIN_URL = '<?php echo SKIN_URL ?>';
</script>

</head>
<body>
<?php $this->partial('content') ?>
</body>
</html>
