<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Error 404</title>

<link rel="stylesheet" href="<?php echo SKIN_URL ?>/css/style.css" />

<script type="text/javascript">
SKIN_URL = '<?php echo SKIN_URL ?>';
</script>


</head>
<body>
 <h1 style="text-align: center; color: white; margin: 0 auto; padding-top: 100px;">404 Page not found.</h1>

</body>
</html>